# This is a basic workflow to help you get started with Actions

name: Build and deploy docs to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
      - run: mix deps.get
      - run: mix docs

      - name: Publish docs to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: doc
          target-branch: gh_pages
